/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#2d476f',
        'surface-container-high': '#eae7e7',
        'surface-bright': '#fcf9f8',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#aec7f6',
        'background': '#fcf9f8',
        'primary-fixed-dim': '#aec7f6',
        'on-surface': '#1b1c1c',
        'primary-fixed': '#d6e3ff',
        'secondary-container': '#fed65b',
        'surface': '#fcf9f8',
        'on-secondary-container': '#745c00',
        'inverse-surface': '#303030',
        'surface-container': '#f0eded',
        'primary': '#000a1e',
        'tertiary': '#0b0c02',
        'on-secondary-fixed-variant': '#574500',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#898b75',
        'on-background': '#1b1c1c',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#474836',
        'on-secondary-fixed': '#241a00',
        'on-surface-variant': '#44474e',
        'error': '#ba1a1a',
        'surface-container-low': '#f6f3f2',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#c8c8b0',
        'outline-variant': '#c4c6cf',
        'error-container': '#ffdad6',
        'surface-dim': '#dcd9d9',
        'on-tertiary-fixed': '#1b1d0e',
        'outline': '#74777f',
        'tertiary-fixed': '#e4e4cc',
        'surface-variant': '#e4e2e1',
        'secondary-fixed-dim': '#e9c349',
        'secondary-fixed': '#ffe088',
        'surface-container-highest': '#e4e2e1',
        'inverse-on-surface': '#f3f0f0',
        'surface-tint': '#465f88',
        'tertiary-container': '#212313',
        'on-primary-container': '#708ab5',
        'secondary': '#735c00',
        'on-primary-fixed': '#001b3d',
        'on-error-container': '#93000a',
        'primary-container': '#002147',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-md': '16px',
        'unit': '8px',
        'container-padding': '20px',
        'stack-sm': '8px',
        'gutter': '16px',
        'stack-lg': '32px',
      },
      fontFamily: {
        h1: ['Newsreader'],
        h2: ['Newsreader'],
        h3: ['Newsreader'],
        'body-md': ['Public Sans'],
        'body-lg': ['Public Sans'],
        button: ['Public Sans'],
        'label-caps': ['Public Sans'],
        serif: ['Newsreader', 'Georgia', 'serif'],
        sans: ['Public Sans', 'sans-serif'],
      },
      fontSize: {
        h1: ['34px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        h2: ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['22px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '400' }],
        button: ['16px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
