/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e4e2e1',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#44474e',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f3f0f0',
        outline: '#74777f',
        'outline-variant': '#c4c6cf',
        'surface-tint': '#465f88',
        primary: '#000a1e',
        'on-primary': '#ffffff',
        'primary-container': '#002147',
        'on-primary-container': '#708ab5',
        'inverse-primary': '#aec7f6',
        secondary: '#735c00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed65b',
        'on-secondary-container': '#745c00',
        tertiary: '#0b0c02',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#212313',
        'on-tertiary-container': '#898b75',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fcf9f8',
        'on-background': '#1b1c1c',
        'surface-variant': '#e4e2e1',
      },
      fontFamily: {
        serif: ['Newsreader', 'Georgia', 'serif'],
        sans: ['Public Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
