export const quizSeedPropertyWK14 = [
  {
    courseId: 5,
    topicName: 'WK 14: Billing and Accounting',
    scenarios: [],
    questions: [
      { prompt: 'Franklin Chukwuebuka SAN is the Principal Partner of a law firm. Gateway Properties Nig. Ltd was indebted to his firm for \u20a615,000,000. What is the step that Franklin Chukwuebuka SAN will take to recover this debt?', options: ['a. Send a bill of charges to Gateway Properties Nig. Ltd', 'b. Beg Gateway Properties Nig. Ltd to pay', 'c. Resort to self help', 'd. Instruct a colleague to write a letter of demand to Gateway Properties Nig. Ltd'], correct: 0, explanation: 'The first step is to prepare a Bill of charges, which should set out the particulars of the principal claims and send to the client.' },
      { prompt: 'Which court has original jurisdiction to entertain the matter if Franklin Chukwuebuka SAN decides to institute an action?', options: ['a. District Court', 'b. Debt Recovery Tribunal', 'c. High Court of Justice', 'd. Multi-Door Court House'], correct: 2, explanation: 'The Court with jurisdiction in recovery of professional fee is the State High Court or the High Court of the FCT. Sec. 19(1), LPA.' },
      { prompt: 'The appropriate mode of commencement of action for the recovery of professional fee in the court you have identified above is?', options: ['a. Originating Summons', 'b. Writ of summons', 'c. Claims', 'd. Originating application'], correct: 1, explanation: '' },
      { prompt: 'If Franklin Chukwuebuka SAN were to send a bill charges to Gateway Properties Nigeria Ltd., what is the stipulated period that he would give the company before he can institute an action?', options: ['a. 21 days', 'b. 31 days', 'c. 30 days', 'd. One month'], correct: 3, explanation: 'The words used by the Act are one month. There is a difference between 30 days and one month.' },
      { prompt: 'A solicitor acting for both the lessor and lessee in a lease transaction shall be entitled to his professional fee as follows:', options: ['a. Full payment from the lessee and half payment from the lessor', 'b. Full payment from the lessor and half of the lessee\'s fee', 'c. Full payment from the lessor and quarter of lessor\'s fee from the lessee', 'd. B and C'], correct: 3, explanation: 'In leases, the lessor\'s solicitor is entitled to the full charges, while the lessee\'s solicitor is entitled to half. Where a solicitor acts for both parties, he will be entitled to full charges from the lessor plus half of what is due to the lessee\'s solicitor or quarter of lessor\'s fee.' },
      { prompt: 'Where a solicitor acts for both the mortgagor and mortgagee, he is entitled to:', options: ['a. Full payment from both mortgagor and mortgagee', 'b. Full payment from mortgagee and half payment from mortgagor', 'c. Full payment from mortgagor and half payment from mortgagee', 'd. Half payment from both mortgagor and mortgagee'], correct: 1, explanation: 'Fee of a solicitor who acts for both parties in a mortgage is calculated: full from the mortgagee according to the scale, and half from the mortgagor according to the scale.' },
      { prompt: 'Iyinoluwa Ajayi bought a duplex from Oluwaseun Oyekan for \u20a630,000,000. Both parties engaged Mujib Jimoh Esq. The relevant law being referred to in the scenario above is the:', options: ['a. Rules of Professional Conduct', 'b. Legal practitioners Act', 'c. Legal practitioners Account Rules', 'd. Legal practitioners\' Remuneration for Legal Documentation and other Land Matters Order'], correct: 3, explanation: '' },
      { prompt: 'Mujib Jimoh will charge his professional fee under what scale of the law above?', options: ['a. Scale III', 'b. Scale II', 'c. Scale I', 'd. Scale IV'], correct: 2, explanation: 'Scale I deals with completed transactions of sale, purchase or mortgage.' },
      { prompt: 'In calculating his professional fees under the relevant scale for representing both parties, Mujib Jimoh will be entitled to:', options: ['a. Full payment from both the Assignor and Assignee', 'b. Full payment from the Assignee and half payment from the Assignor', 'c. Full payment from the Assignor and half payment from the Assignee', 'd. Full payment from the Assignee and quarter of Assignee\'s fee from Assignor'], correct: 0, explanation: 'In Assignment, a solicitor acting for both parties is entitled to full payment from both the Assignor and the Assignee.' },
      { prompt: 'Assuming Mujib Jimoh decides to charge his professional fee using Scale III, one of the following is not a factor to be considered:', options: ['a. Value of the property involved', 'b. The time expended by him in the transaction', 'c. Complexity, novelty and difficulty of the matter', 'd. None of the above'], correct: 3, explanation: '' },
      { prompt: 'In late Mr. Akerodolu Mimiko\'s Will, he gave one of his concubines his 4 storey building in Ikoyi. Mr Chuks contested the Will and instructed Mr. Wiliki. Mr. Wiliki can charge all the following types of fee in the above scenario except___:', options: ['a. Contingent fee', 'b. Appearance fee', 'c. Scale fee', 'd. None of the above'], correct: 2, explanation: 'The transaction is contentious. Scale fee is only used when the transaction involves legal documentation or non-contentious matters.' },
      { prompt: 'If Mr. Chuks feels the Bill served on him by Mr. Wiliki is outrageous and wishes to review it, he could opt for one of the following options:', options: ['a. Apply to Court for bills of cost review', 'b. File an action in court to mandate Mr. Wiliki to prove the Bill', 'c. Request for taxation of the Bill', 'd. None of the above'], correct: 2, explanation: 'Sec. 17 LPA.' },
      { prompt: 'The appropriate court Mr. Chuks can go to for the option you have identified above is?', options: ['a. The High Court', 'b. The Magistrate Court', 'c. The Rent Tribunal', 'd. The Court of Appeal'], correct: 0, explanation: 'Sec. 19 LPA \'Court\'.' },
      { prompt: 'What is the time limit for exercising the option after receipt of the Bill of charges by Mr. Chuks?', options: ['a. Within 10 days', 'b. Within 1 month', 'c. Within 20 days', 'd. Within 2 months'], correct: 1, explanation: 'Sec. 17(2), LPA.' },
      { prompt: 'Legal services such as searches at the Land Registry and the Corporate Affairs Commission can be charged under what scale of the Bill of Charges?', options: ['a. Scale IV', 'b. Scale III', 'c. Scale II', 'd. Scale I'], correct: 1, explanation: 'Searches at the land registry and CAC may be charged under scale III as they are not completed transactions of sale, purchase or mortgage.' },
    ]
  }
];
