export const quizSeedPropertyWK20 = [
  {
    courseId: 5,
    topicName: 'WK 20: Property Law Taxation',
    scenarios: [],
    questions: [
      { prompt: 'Mr. Boniface Okoro lives solely on rents collected from tenants. The tax he would pay in respect of the rent collected would be:', options: ['a. Capital Gains Tax', 'b. Personal Income Tax', 'c. Value Added Tax', 'd. All of the above'], correct: 1, explanation: 'The rent is deemed to be an income accruing to the lessor; thus he will pay Personal Income Tax. Capital Gains Tax is payable where there is a sale of land for profit.' },
      { prompt: 'The tax expected to be paid in respect of land with buildings erected on it is:', options: ['a. Ground rent', 'b. Tenement rate', 'c. Land use rate', 'd. Ground use rate'], correct: 1, explanation: '' },
      { prompt: 'The professional fee of your principal in respect of any sale of land while acting as solicitor to Capital Investments Ltd form part of _____ under the Capital Gains Tax Act?', options: ['a. Accruable Income', 'b. Allowable income', 'c. Taxable income', 'd. Allowable expenses'], correct: 3, explanation: 'In calculating CGT, allowable expenses are deducted, which includes professional fees paid to a solicitor involved in the sale. Sec. 13 & 14, CGTA.' },
      { prompt: 'Assuming one of the properties was sold for \u20a65,000,000, with Advertisement = \u20a6500,000, Renovation = \u20a6900,000, professional charges = \u20a6500,000 and initial purchase price = \u20a6100,000. The Capital Gains Tax payable would be:', options: ['a. \u20a6300,000', 'b. \u20a63,000,000', 'c. \u20a630,000', 'd. \u20a6100,000'], correct: 0, explanation: 'Total allowable expenses = \u20a62,000,000. Amount of sale = \u20a65,000,000. Deduct expenses: \u20a63,000,000. 10% of \u20a63,000,000 = \u20a6300,000.' },
      { prompt: 'The stamp duty payable by Capital Investments Ltd in respect of the sale of the property is to be paid to the__:', options: ['a. Minister of Finance', 'b. Lagos State Board of Internal Revenue', 'c. Federal Inland Revenue Service', 'd. Lagos State Commissioner of Finance'], correct: 2, explanation: 'Taxes payable by companies are paid to the Federal Inland Revenue Service.' },
      { prompt: 'One of the following best describes the tax(es) payable by a vendor when he sells property at a profit:', options: ['a. Capital Gains Tax', 'b. Value Added Tax', 'c. Personal Income Tax', 'd. A and B'], correct: 0, explanation: '' },
      { prompt: 'The tax payable in respect of the estate of a testator during the execution of the Will is:', options: ['a. Consent fee', 'b. Stamp duties', 'c. Testament duties', 'd. Estate Duties'], correct: 3, explanation: '' },
      { prompt: 'One of the following transactions would warrant the payment of Capital Gains Tax:', options: ['a. Mortgage of a property to a bank for a loan', 'b. Sale of property by personal representatives to raise money for the estate of the deceased', 'c. Sale of property by the Redeemed Christian Church of God', 'd. None of the above'], correct: 1, explanation: 'Where personal representatives sell his property to raise money for his estate, CGT would be paid on the profit. But if they merely convey to beneficiaries, CGT is not payable. The Redeemed Christian Church of God is exempted from CGT. Section 26 CGT Act.' },
      { prompt: 'The direct beneficiary of tenement rates is:', options: ['a. The Federal Government', 'b. The State Government', 'c. The Local Government', 'd. All of the above'], correct: 2, explanation: 'Local governments collect tenement rates and are the direct beneficiaries.' },
      { prompt: 'In calculating Capital Gains Tax, the following are allowable expenses except:', options: ['a. Amount paid for the acquisition of the asset', 'b. Money spent on establishing or defending right over the asset', 'c. Incidental cost to the disposal of the asset, like advertisement', 'd. Monetary value of direct labour put into the improvement of the property by the vendor'], correct: 3, explanation: 'The monetary value of direct labour put into improvement of a property is not part of allowable expenses. Cram v Johnson.' },
      { prompt: 'Mrs. Osehun Moses bought a duplex at Ikoyi, Lagos for \u20a61,000,000. She renovated for \u20a6500,000 and sold for \u20a66,000,000 after advertising for \u20a6500,000. The following taxes would be payable on gains realised:', options: ['a. Capital Gains Tax, Consent fee and Stamp Duty', 'b. Stamp Duty and Ground Rent', 'c. Rent, Tenement, Development Levy', 'd. Registration Fee, Value Added Tax, Stamp Duties'], correct: 0, explanation: '' },
      { prompt: 'What could exempt Mrs Osehun Moses from paying tax?', options: ['a. Ecclesiastical or charitable organisation', 'b. Disposition by way of gift', 'c. Gains accruing to local government', 'd. None of the above'], correct: 1, explanation: 'Since Osehun Moses is not a charitable or religious organization, what could exempt her from paying CGT is where she disposed the property by way of gift.' },
      { prompt: 'What formula will be applied in computing Capital Gains Tax?', options: ['a. 10% of gain', 'b. Consideration minus allowable income', 'c. All of the above', 'd. None of the above'], correct: 2, explanation: 'The formula for calculating CGT is 10% of the gain realizable from the sale. But the gain realized is from a subtraction of allowable expenses from the consideration.' },
      { prompt: 'Which of the following taxes is payable to the Federal Government?', options: ['a. Companies Income Tax', 'b. Consent fee', 'c. Right of Occupancy fees', 'd. None of the above'], correct: 0, explanation: 'Companies Income Tax is payable to the Federal Government through the FIRS.' },
      { prompt: 'The following are correct about personal income tax except:', options: ['a. Taxable persons include companies, individuals, trustees, charitable entities and communities', 'b. Chargeable income of partners of a business include salary and shared profit', 'c. Rent paid in advance are chargeable', 'd. All of the above'], correct: 0, explanation: 'Companies do not pay Personal income tax; they pay company income tax and charitable organizations are exempted from the payment of tax.' },
    ]
  }
];
